# Generated by Django 5.0.1 on 2025-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileversion",
            name="can_read",
            field=models.BooleanField(default=True, help_text="Can this file be read by the owner?"),
        ),
        migrations.AddField(
            model_name="fileversion",
            name="can_write",
            field=models.BooleanField(default=True, help_text="Can this file be overwritten by the owner?"),
        ),
    ]
